version: '3.8'
services:
  postgres:
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    env_file:
      - .env

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/var/lib/redis/data/
    restart: on-failure
    ports:
      - "6379:6379"
    env_file:
      - .env

  bot:
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env


volumes:
  postgres_data:
  redis_data:
